# -*- coding: utf-8 -*-
"""
Created on Tue Aug 28 10:07:42 2018

@author: makraus
"""
icd9_to_description = {
0: ' ',
1: ' ',
2: ' ',
3: ' ',
4: ' ',
5: ' ',
6: ' ',
7: ' ',
8: ' ',
9: ' ',
11: ' ',
15: ' ',
16: ' ',
17: ' ',
18: ' ',
23: ' ',
31: ' ',
33: ' ',
34: ' ',
35: ' ',
36: ' ',
38: ' ',
39: ' ',
40: ' ',
41: ' ',
43: ' ',
44: ' ',
45: ' ',
47: ' ',
49: ' ',
51: ' ',
52: ' ',
53: ' ',
54: ' ',
55: ' ',
57: ' ',
70: ' ',
72: ' ',
74: ' ',
75: ' ',
76: ' ',
77: ' ',
78: ' ',
79: 'Viral infection in conditions classified elsewhere and of unspecified site',
81: ' ',
82: ' ',
83: ' ',
84: ' ',
85: ' ',
87: ' ',
88: ' ',
89: ' ',
91: ' ',
92: ' ',
93: ' ',
94: ' ',
95: ' ',
96: ' ',
97: ' ',
98: ' ',
99: ' ',
101: 'Vincents angina',
102: 'Yaws',
110: 'Dermatophytosis',
111: 'Dermatomycosis, other and unspecified',
112: 'Candidiasis',
116: 'Blastomycotic infection',
117: 'Other mycoses',
120: 'Schistosomiasis [bilharziasis]',
122: 'Echinococcosis',
125: 'Filarial infection and dracontiasis',
127: 'Other intestinal helminthiases',
128: 'Other and unspecified helminthiases',
129: 'Intestinal parasitism, unspecified',
130: 'Toxoplasmosis',
131: 'Trichomoniasis',
132: 'Pediculosis and phthirus infestation',
133: 'Acariasis',
134: 'Other infestation',
135: 'Sarcoidosis',
136: 'Other and unspecified infectious and parasitic diseases',
137: 'Late effects of tuberculosis',
138: 'Late effects of acute poliomyelitis',
141: 'Malignant neoplasm of tongue',
142: 'Malignant neoplasm of major salivary glands',
146: 'Malignant neoplasm of oropharynx',
147: 'Malignant neoplasm of nasopharynx',
148: 'Malignant neoplasm of hypopharynx',
150: 'Malignant neoplasm of esophagus',
151: 'Malignant neoplasm of stomach',
152: 'Malignant neoplasm of small intestine, including duodenum',
153: 'Malignant neoplasm of colon',
154: 'Malignant neoplasm of rectum, rectosigmoid junction, and anus',
155: 'Malignant neoplasm of liver and intrahepatic bile ducts',
156: 'Malignant neoplasm of gallbladder and extrahepatic bile ducts',
157: 'Malignant neoplasm of pancreas',
158: 'Malignant neoplasm of retroperitoneum and peritoneum',
159: 'Malignant neoplasm of other and ill-defined sites within the digestive organs and peritoneum',
160: 'Malignant neoplasm of nasal cavities, middle ear, and accessory sinuses',
161: 'Malignant neoplasm of larynx',
162: 'Malignant neoplasm of trachea, bronchus, and lung',
164: 'Malignant neoplasm of thymus, heart, and mediastinum',
165: 'Malignant neoplasm of other and ill-defined sites within the respiratory system and intrathoracic organs',
170: 'Malignant neoplasm of bone and articular cartilage',
171: 'Malignant neoplasm of connective and other soft tissue',
172: 'Malignant melanoma of skin',
173: 'Other malignant neoplasm of skin',
174: 'Malignant neoplasm of female breast',
175: 'Malignant neoplasm of male breast',
176: 'Kaposis sarcoma',
179: 'Malignant neoplasm of uterus, part unspecified',
180: 'Malignant neoplasm of cervix uteri',
182: 'Malignant neoplasm of body of uterus',
183: 'Malignant neoplasm of ovary and other uterine adnexa',
185: 'Malignant neoplasm of prostate',
186: 'Malignant neoplasm of testis',
187: 'Malignant neoplasm of penis and other male genital organs',
188: 'Malignant neoplasm of bladder',
189: 'Malignant neoplasm of kidney and other and unspecified urinary organs',
190: 'Malignant neoplasm of eye',
191: 'Malignant neoplasm of brain',
192: 'Malignant neoplasm of other and unspecified parts of nervous system',
193: 'Malignant neoplasm of thyroid gland',
194: 'Malignant neoplasm of other endocrine glands and related structures',
195: 'Malignant neoplasm of other and ill-defined sites',
197: 'Secondary malignant neoplasm of respiratory and digestive systems',
198: 'Secondary malignant neoplasm of other specified sites',
199: 'Malignant neoplasm without specification of site',
200: 'Lymphosarcoma and reticulosarcoma and other specified malignant tumors of lymphatic tissue',
201: 'Hodgkins disease',
202: 'Other malignant neoplasms of lymphoid and histiocytic tissue',
203: 'Multiple myeloma and immunoproliferative neoplasms',
204: 'Lymphoid leukemia',
205: 'Myeloid leukemia',
206: 'Monocytic leukemia',
208: 'Leukemia of unspecified cell type',
210: 'Benign neoplasm of lip, oral cavity, and pharynx',
211: 'Benign neoplasm of other parts of digestive system',
212: 'Benign neoplasm of respiratory and intrathoracic organs',
213: 'Benign neoplasm of bone and articular cartilage',
214: 'Lipoma',
215: 'Other benign neoplasm of connective and other soft tissue',
216: 'Benign neoplasm of skin',
217: 'Benign neoplasm of breast',
218: 'Uterine leiomyoma',
219: 'Other benign neoplasm of uterus',
220: 'Benign neoplasm of ovary',
221: 'Benign neoplasm of other female genital organs',
222: 'Benign neoplasm of male genital organs',
223: 'Benign neoplasm of kidney and other urinary organs',
224: 'Benign neoplasm of eye',
225: 'Benign neoplasm of brain and other parts of nervous system',
226: 'Benign neoplasm of thyroid glands',
227: 'Benign neoplasm of other endocrine glands and related structures',
228: 'Hemangioma and lymphangioma, any site',
229: 'Benign neoplasm of other and unspecified sites',
230: 'Carcinoma in situ of digestive organs',
231: 'Carcinoma in situ of respiratory system',
232: 'Carcinoma in situ of skin',
233: 'Carcinoma in situ of breast and genitourinary system',
234: 'Carcinoma in situ of other and unspecified sites',
235: ' ',
236: 'Neoplasm of uncertain behavior of genitourinary organs',
237: 'Neoplasm of uncertain behavior of endocrine glands and nervous system',
238: 'Neoplasm of uncertain behavior of other and unspecified sites and tissues',
239: 'NEOPLASMS OF UNSPECIFIED NATURE ',
240: 'Simple and unspecified goiter',
241: 'Nontoxic nodular goiter',
242: 'Thyrotoxicosis with or without goiter',
244: 'Acquired hypothyroidism',
245: 'Thyroiditis',
246: 'Other disorders of thyroid',
250: 'Diabetes mellitus',
251: 'Other disorders of pancreatic internal secretion',
252: 'Disorders of parathyroid gland',
253: 'Disorders of the pituitary gland and its hypothalamic control',
254: 'Diseases of thymus gland',
255: 'Disorders of adrenal glands',
256: 'Ovarian dysfunction',
257: 'Testicular dysfunction',
258: 'Polyglandular dysfunction and related disorders',
259: 'Other endocrine disorders',
263: 'Other and unspecified protein-calorie malnutrition',
264: 'Vitamin A deficiency',
266: 'Deficiency of B-complex components',
267: 'Ascorbic acid deficiency',
268: 'Vitamin D deficiency',
269: 'Other nutritional deficiencies',
270: 'Disorders of amino-acid transport and metabolism',
271: 'Disorders of carbohydrate transport and metabolism',
272: 'Disorders of lipoid metabolism',
273: 'Disorders of plasma protein metabolism',
274: 'Gout',
275: 'Disorders of mineral metabolism',
276: 'Disorders of fluid, electrolyte, and acid-base balance',
277: 'Other and unspecified disorders of metabolism',
278: 'Overweight, obesity and other hyperalimentation',
279: 'Disorders involving the immune mechanism',
280: ' ',
281: ' ',
282: ' ',
283: ' ',
284: ' ',
285: ' ',
286: ' ',
287: ' ',
288: ' ',
289: ' ',
290: 'Dementias',
291: 'Alcohol-induced mental disorders',
292: 'Drug-induced mental disorders',
293: 'Transient mental disorders due to conditions classified elsewhere',
294: 'Persistent mental disorders due to conditions classified elsewhere',
295: 'Schizophrenic disorders',
296: 'Episodic mood disorders',
297: 'Delusional disorders',
298: 'Other nonorganic psychoses',
300: 'Anxiety, dissociative and somatoform disorders',
301: 'Personality disorders',
302: 'Sexual and gender identity disorders',
303: 'Alcohol dependence syndrome',
304: 'Drug dependence',
305: 'Nondependent abuse of drugs',
306: 'Physiological malfunction arising from mental factors',
307: 'Special symptoms or syndromes, not elsewhere classified',
308: 'Acute reaction to stress',
309: 'Adjustment reaction',
310: 'Specific nonpsychotic mental disorders due to brain damage',
311: 'Depressive disorder, not elsewhere classified',
312: 'Disturbance of conduct, not elsewhere classified',
314: 'Hyperkinetic syndrome of childhood',
315: 'Specific delays in development',
316: 'Psychic factors associated with diseases classified elsewhere',
317: 'Mild mental retardation',
318: 'Other specified mental retardation',
319: 'Unspecified mental retardation',
320: 'Bacterial meningitis',
322: 'Meningitis of unspecified cause',
323: 'Encephalitis, myelitis, and encephalomyelitis',
324: 'Intracranial and intraspinal abscess',
331: 'Other cerebral degenerations',
332: 'Parkinsons disease',
333: 'Other extrapyramidal disease and abnormal movement disorders',
334: 'Spinocerebellar disease',
335: 'Anterior horn cell disease',
336: 'Other diseases of spinal cord',
337: 'Disorders of the autonomic nervous system',
340: 'Multiple sclerosis',
341: 'Other demyelinating diseases of central nervous system',
342: 'Hemiplegia and hemiparesis',
343: 'Infantile cerebral palsy',
344: 'Other paralytic syndromes',
345: 'Epilepsy and recurrent seizures',
346: 'Migraine',
347: 'Cataplexy and narcolepsy',
348: 'Other conditions of brain',
349: 'Other and unspecified disorders of the nervous system',
350: 'Trigeminal nerve disorders',
351: 'Facial nerve disorders',
352: 'Disorders of other cranial nerves',
353: 'Nerve root and plexus disorders',
354: 'Mononeuritis of upper limb and mononeuritis multiplex',
355: 'Mononeuritis of lower limb',
356: 'Hereditary and idiopathic peripheral neuropathy',
357: 'Inflammatory and toxic neuropathy',
358: 'Myoneural disorders',
359: 'Muscular dystrophies and other myopathies',
360: 'Disorders of the globe',
361: 'Retinal detachments and defects',
362: 'Other retinal disorders',
363: 'Chorioretinal inflammations, scars, and other disorders of choroid',
364: 'Disorders of iris and ciliary body',
365: 'Glaucoma',
366: 'Cataract',
367: 'Disorders of refraction and accommodation',
368: 'Visual disturbances',
369: 'Blindness and low vision',
370: 'Keratitis',
371: 'Corneal opacity and other disorders of cornea',
372: 'Disorders of conjunctiva',
373: 'Inflammation of eyelids',
374: 'Other disorders of eyelids',
375: 'Disorders of lacrimal system',
376: 'Disorders of the orbit',
377: 'Disorders of optic nerve and visual pathways',
378: 'Strabismus and other disorders of binocular eye movements',
379: 'Other disorders of eye',
380: 'Disorders of external ear',
381: 'Nonsuppurative otitis media and Eustachian tube disorders',
382: 'Suppurative and unspecified otitis media',
383: 'Mastoiditis and related conditions',
384: 'Other disorders of tympanic membrane',
385: 'Other disorders of middle ear and mastoid',
386: 'Vertiginous syndromes and other disorders of vestibular system',
387: 'Otosclerosis',
388: 'Other disorders of ear',
389: 'Hearing loss',
390: 'Rheumatic fever without mention of heart involvement',
391: 'Rheumatic fever with heart involvement',
393: 'Chronic rheumatic pericarditis',
394: 'Diseases of mitral valve',
395: 'Diseases of aortic valve',
396: 'Diseases of mitral and aortic valves',
397: 'Diseases of other endocardial structures',
398: 'Other rheumatic heart disease',
401: 'Essential hypertension',
402: 'Hypertensive heart disease',
403: 'Hypertensive chronic kidney disease',
404: 'Hypertensive heart and chronic kidney disease',
405: 'Secondary hypertension',
410: 'Acute myocardial infarction',
411: 'Other acute and subacute forms of ischemic heart disease',
412: 'Old myocardial infarction',
413: 'Angina pectoris',
414: 'Other forms of chronic ischemic heart disease',
415: 'Acute pulmonary heart disease',
416: 'Chronic pulmonary heart disease',
420: 'Acute pericarditis',
421: 'Acute and subacute endocarditis',
422: 'Acute myocarditis',
423: 'Other diseases of pericardium',
424: 'Other diseases of endocardium',
425: 'Cardiomyopathy',
426: 'Conduction disorders',
427: 'Cardiac dysrhythmias',
428: 'Heart failure',
429: 'Ill-defined descriptions and complications of heart disease',
430: 'Subarachnoid hemorrhage',
431: 'Intracerebral hemorrhage',
432: 'Other and unspecified intracranial hemorrhage',
433: 'Occlusion and stenosis of precerebral arteries',
434: 'Occlusion of cerebral arteries',
435: 'Transient cerebral ischemia',
436: 'Acute, but ill-defined, cerebrovascular disease',
437: 'Other and ill-defined cerebrovascular disease',
438: 'Late effects of cerebrovascular disease',
440: 'Atherosclerosis',
441: 'Aortic aneurysm and dissection',
442: 'Other aneurysm',
443: 'Other peripheral vascular disease',
444: 'Arterial embolism and thrombosis',
446: 'Polyarteritis nodosa and allied conditions',
447: 'Other disorders of arteries and arterioles',
448: 'Disease of capillaries',
451: 'Phlebitis and thrombophlebitis',
452: 'Portal vein thrombosis',
453: 'Other venous embolism and thrombosis',
454: 'Varicose veins of lower extremities',
455: 'Hemorrhoids',
456: 'Varicose veins of other sites',
457: 'Noninfectious disorders of lymphatic channels',
458: 'Hypotension',
459: 'Other disorders of circulatory system',
460: 'Acute nasopharyngitis [common cold]',
461: 'Acute sinusitis',
462: 'Acute pharyngitis',
463: 'Acute tonsillitis',
464: 'Acute laryngitis and tracheitis',
465: 'Acute upper respiratory infections of multiple or unspecified sites',
466: 'Acute bronchitis and bronchiolitis',
470: 'Deviated nasal septum',
471: 'Nasal polyps',
472: 'Chronic pharyngitis and nasopharyngitis',
473: 'Chronic sinusitis',
474: 'Chronic disease of tonsils and adenoids',
475: 'Peritonsillar abscess',
476: 'Chronic laryngitis and laryngotracheitis',
477: 'Allergic rhinitis',
478: 'Other diseases of upper respiratory tract',
480: 'Viral pneumonia',
481: 'Pneumococcal pneumonia [Streptococcus pneumoniae pneumonia]',
482: 'Other bacterial pneumonia',
483: 'Pneumonia due to other specified organism',
484: 'Pneumonia in infectious diseases classified elsewhere',
485: 'Bronchopneumonia, organism unspecified',
486: 'Pneumonia, organism unspecified',
487: 'Influenza',
490: 'Bronchitis, not specified as acute or chronic',
491: 'Chronic bronchitis',
492: 'Emphysema',
493: 'Asthma',
494: 'Bronchiectasis',
495: 'Extrinsic allergic alveolitis',
496: 'Chronic airway obstruction, not elsewhere classified',
501: 'Asbestosis',
502: 'Pneumoconiosis due to other silica or silicates',
505: 'Pneumoconiosis, unspecified',
506: 'Respiratory conditions due to chemical fumes and vapors',
507: 'Pneumonitis due to solids and liquids',
508: 'Respiratory conditions due to other and unspecified external agents',
510: 'Empyema',
511: 'Pleurisy',
512: 'Pneumothorax',
513: 'Abscess of lung and mediastinum',
514: 'Pulmonary congestion and hypostasis',
515: 'Postinflammatory pulmonary fibrosis',
516: 'Other alveolar and parietoalveolar pneumonopathy',
517: 'Lung involvement in conditions classified elsewhere',
518: 'Other diseases of lung',
519: 'Other diseases of respiratory system',
520: 'Disorders of tooth development and eruption',
521: 'Diseases of hard tissues of teeth',
522: 'Diseases of pulp and periapical tissues',
523: 'Gingival and periodontal diseases',
524: 'Dentofacial anomalies, including malocclusion',
525: 'Other diseases and conditions of the teeth and supporting structures',
526: 'Diseases of the jaws',
527: 'Diseases of the salivary glands',
528: 'Diseases of the oral soft tissues, excluding lesions specific for gingiva and tongue',
529: 'Diseases and other conditions of the tongue',
530: 'Diseases of esophagus',
531: 'Gastric ulcer',
532: 'Duodenal ulcer',
533: 'Peptic ulcer, site unspecified',
535: 'Gastritis and duodenitis',
536: 'Disorders of function of stomach',
537: 'Other disorders of stomach and duodenum',
540: 'Acute appendicitis',
541: 'Appendicitis, unqualified',
542: 'Other appendicitis',
550: 'Inguinal hernia',
551: 'Other hernia of abdominal cavity, with gangrene',
552: 'Other hernia of abdominal cavity, with obstruction, but without mention of gangrene',
553: 'Other hernia of abdominal cavity without mention of obstruction or gangrene',
555: 'Regional enteritis',
556: 'Ulcerative colitis',
557: 'Vascular insufficiency of intestine',
558: 'Other and unspecified noninfectious gastroenteritis and colitis',
560: 'Intestinal obstruction without mention of hernia',
562: 'Diverticula of intestine',
564: 'Functional digestive disorders, not elsewhere classified',
565: 'Anal fissure and fistula',
566: 'Abscess of anal and rectal regions',
567: 'Peritonitis and retroperitoneal infections',
568: 'Other disorders of peritoneum',
569: 'Other disorders of intestine',
571: 'Chronic liver disease and cirrhosis',
572: 'Liver abscess and sequelae of chronic liver disease',
573: 'Other disorders of liver',
574: 'Cholelithiasis',
575: 'Other disorders of gallbladder',
576: 'Other disorders of biliary tract',
577: 'Diseases of pancreas',
578: 'Gastrointestinal hemorrhage',
579: 'Intestinal malabsorption',
580: 'Acute glomerulonephritis',
581: 'Nephrotic syndrome',
582: 'Chronic glomerulonephritis',
583: 'Nephritis and nephropathy, not specified as acute or chronic',
584: 'Acute renal failure',
585: 'Chronic kidney disease (CKD)',
586: 'Renal failure, unspecified',
588: 'Disorders resulting from impaired renal function',
589: 'Small kidney of unknown cause',
590: 'Infections of kidney',
591: 'Hydronephrosis',
592: 'Calculus of kidney and ureter',
593: 'Other disorders of kidney and ureter',
594: 'Calculus of lower urinary tract',
595: 'Cystitis',
596: 'Other disorders of bladder',
597: 'Urethritis, not sexually transmitted, and urethral syndrome',
598: 'Urethral stricture',
599: 'Other disorders of urethra and urinary tract',
600: 'Hyperplasia of prostate',
601: 'Inflammatory diseases of prostate',
602: 'Other disorders of prostate',
603: 'Hydrocele',
604: 'Orchitis and epididymitis',
605: 'Redundant prepuce and phimosis',
606: 'Infertility, male',
607: 'Disorders of penis',
608: 'Other disorders of male genital organs',
610: 'Benign mammary dysplasias',
611: 'Other disorders of breast',
614: 'Inflammatory disease of ovary, fallopian tube, pelvic cellular tissue, and peritoneum',
615: 'Inflammatory diseases of uterus, except cervix',
616: 'Inflammatory disease of cervix, vagina, and vulva',
617: 'Endometriosis',
618: 'Genital prolapse',
619: 'Fistula involving female genital tract',
620: 'Noninflammatory disorders of ovary, fallopian tube, and broad ligament',
621: 'Disorders of uterus, not elsewhere classified',
622: 'Noninflammatory disorders of cervix',
623: 'Noninflammatory disorders of vagina',
624: 'Noninflammatory disorders of vulva and perineum',
625: 'Pain and other symptoms associated with female genital organs',
626: 'Disorders of menstruation and other abnormal bleeding from female genital tract',
627: 'Menopausal and postmenopausal disorders',
628: 'Infertility, female',
629: 'Other disorders of female genital organs',
630: 'Hydatidiform mole',
631: 'Other abnormal product of conception',
632: 'Missed abortion',
633: 'Ectopic pregnancy',
634: 'Spontaneous abortion',
635: 'Legally induced abortion',
636: 'Illegally induced abortion',
640: 'Hemorrhage in early pregnancy',
641: 'Antepartum hemorrhage, abruptio placentae, and placenta previa',
642: 'Hypertension complicating pregnancy, childbirth, and the puerperium',
643: 'Excessive vomiting in pregnancy',
644: 'Early or threatened labor',
645: 'Late pregnancy',
646: 'Other complications of pregnancy, not elsewhere classified',
647: 'Infectious and parasitic conditions in the mother classifiable elsewhere, but complicating pregnancy, childbirth, or the puerperium',
648: 'Other current conditions in the mother classifiable elsewhere, but complicating pregnancy, childbirth, or the puerperium',
650: 'Normal delivery',
651: 'Multiple gestation',
652: 'Malposition and malpresentation of fetus',
653: 'Disproportion',
654: 'Abnormality of organs and soft tissues of pelvis',
655: 'Known or suspected fetal abnormality affecting management of mother',
656: 'Other known or suspected fetal and placental problems affecting management of mother',
657: 'Polyhydramnios',
658: 'Other problems associated with amniotic cavity and membranes',
659: 'Other indications for care or intervention related to labor and delivery, not elsewhere classified',
661: 'Abnormality of forces of labor',
663: 'Umbilical cord complications',
664: 'Trauma to perineum and vulva during delivery',
665: 'Other obstetrical trauma',
666: 'Postpartum hemorrhage',
669: 'Other complications of labor and delivery, not elsewhere classified',
671: 'Venous complications in pregnancy and the puerperium',
672: 'Pyrexia of unknown origin during the puerperium',
673: 'Obstetrical pulmonary embolism',
674: 'Other and unspecified complications of the puerperium, not elsewhere classified',
675: 'Infections of the breast and nipple associated with childbirth',
676: 'Other disorders of the breast associated with childbirth and disorders of lactation',
680: 'Carbuncle and furuncle',
681: 'Cellulitis and abscess of finger and toe',
682: 'Other cellulitis and abscess',
683: 'Acute lymphadenitis',
684: 'Impetigo',
685: 'Pilonidal cyst',
686: 'Other local infections of skin and subcutaneous tissue',
690: 'Erythematosquamous dermatosis',
691: 'Atopic dermatitis and related conditions',
692: 'Contact dermatitis and other eczema',
693: 'Dermatitis due to substances taken internally',
694: 'Bullous dermatoses',
695: 'Erythematous conditions',
696: 'Psoriasis and similar disorders',
697: 'Lichen',
698: 'Pruritus and related conditions',
700: 'Corns and callosities',
701: 'Other hypertrophic and atrophic conditions of skin',
702: 'Other dermatoses',
703: 'Diseases of nail',
704: 'Diseases of hair and hair follicles',
705: 'Disorders of sweat glands',
706: 'Diseases of sebaceous glands',
707: 'Chronic ulcer of skin',
708: 'Urticaria',
709: 'Other disorders of skin and subcutaneous tissue',
710: 'Diffuse diseases of connective tissue',
711: 'Arthropathy associated with infections',
712: 'Crystal arthropathies',
713: 'Arthropathy associated with other disorders classified elsewhere',
714: 'Rheumatoid arthritis and other inflammatory polyarthropathies',
715: 'Osteoarthrosis and allied disorders',
716: 'Other and unspecified arthropathies',
717: 'Internal derangement of knee',
718: 'Other derangement of joint',
719: 'Other and unspecified disorders of joint',
720: 'Ankylosing spondylitis and other inflammatory spondylopathies',
721: 'Spondylosis and allied disorders',
722: 'Intervertebral disc disorders',
723: 'Other disorders of cervical region',
724: 'Other and unspecified disorders of back',
725: 'Polymyalgia rheumatica',
726: 'Peripheral enthesopathies and allied syndromes',
727: 'Other disorders of synovium, tendon, and bursa',
728: 'Disorders of muscle, ligament, and fascia',
729: 'Other disorders of soft tissues',
730: 'Osteomyelitis, periostitis, and other infections involving bone',
731: 'Osteitis deformans and osteopathies associated with other disorders classified elsewhere',
732: 'Osteochondropathies',
733: 'Other disorders of bone and cartilage',
734: 'Flat foot',
735: 'Acquired deformities of toe',
736: 'Other acquired deformities of limbs',
737: 'Curvature of spine',
738: 'Other acquired deformity',
741: ' ',
742: ' ',
743: ' ',
744: ' ',
745: ' ',
746: ' ',
747: ' ',
748: ' ',
750: ' ',
751: ' ',
752: ' ',
753: ' ',
754: ' ',
755: ' ',
756: ' ',
757: ' ',
758: ' ',
759: ' ',
760: 'Fetus or newborn affected by maternal conditions which may be unrelated to present pregnancy',
763: 'Fetus or newborn affected by other complications of labor and delivery',
764: 'Slow fetal growth and fetal malnutrition',
767: 'Birth trauma',
768: 'Intrauterine hypoxia and birth asphyxia',
770: 'Other respiratory conditions of fetus and newborn',
771: 'Infections specific to the perinatal period',
772: 'Fetal and neonatal hemorrhage',
778: 'Conditions involving the integument and temperature regulation of fetus and newborn',
779: 'Other and ill-defined conditions originating in the perinatal period',
780: 'General symptoms',
781: 'Symptoms involving nervous and musculoskeletal systems',
782: 'Symptoms involving skin and other integumentary tissue',
783: 'Symptoms concerning nutrition, metabolism, and development',
784: 'Symptoms involving head and neck',
785: 'Symptoms involving cardiovascular system',
786: 'Symptoms involving respiratory system and other chest symptoms',
787: 'Symptoms involving digestive system',
788: 'Symptoms involving urinary system',
789: 'Other symptoms involving abdomen and pelvis',
790: 'Nonspecific findings on examination of blood',
791: 'Nonspecific findings on examination of urine',
792: 'Nonspecific abnormal findings in other body substances',
793: 'Nonspecific abnormal findings on radiological and other examination of body structure',
794: 'Nonspecific abnormal results of function studies',
795: 'Other and nonspecific abnormal cytological, histological, immunological and DNA test findings',
796: 'Other nonspecific abnormal findings',
797: 'Senility without mention of psychosis',
798: 'Sudden death, cause unknown',
799: 'Other ill-defined and unknown causes of morbidity and mortality',
802: 'Fracture of face bones',
803: 'Other and unqualified skull fractures',
805: 'Fracture of vertebral column without mention of spinal cord injury',
806: 'Fracture of vertebral column with spinal cord injury',
807: 'Fracture of rib(s), sternum, larynx, and trachea',
808: 'Fracture of pelvis',
810: 'Fracture of clavicle',
811: 'Fracture of scapula',
812: 'Fracture of humerus',
813: 'Fracture of radius and ulna',
814: 'Fracture of carpal bone(s)',
815: 'Fracture of metacarpal bone(s)',
816: 'Fracture of one or more phalanges of hand',
817: 'Multiple fractures of hand bones',
818: 'Ill-defined fractures of upper limb',
819: 'Multiple fractures involving both upper limbs, and upper limb with rib(s) and sternum',
820: 'Fracture of neck of femur',
821: 'Fracture of other and unspecified parts of femur',
822: 'Fracture of patella',
823: 'Fracture of tibia and fibula',
824: 'Fracture of ankle',
825: 'Fracture of one or more tarsal and metatarsal bones',
826: 'Fracture of one or more phalanges of foot',
827: 'Other, multiple, and ill-defined fractures of lower limb',
829: 'Fracture of unspecified bones',
831: 'Dislocation of shoulder',
832: 'Dislocation of elbow',
833: 'Dislocation of wrist',
834: 'Dislocation of finger',
835: 'Dislocation of hip',
836: 'Dislocation of knee',
837: 'Dislocation of ankle',
838: 'Dislocation of foot',
839: 'Other, multiple, and ill-defined dislocations',
840: 'Sprains and strains of shoulder and upper arm',
841: 'Sprains and strains of elbow and forearm',
842: 'Sprains and strains of wrist and hand',
843: 'Sprains and strains of hip and thigh',
844: 'Sprains and strains of knee and leg',
845: 'Sprains and strains of ankle and foot',
846: 'Sprains and strains of sacroiliac region',
847: 'Sprains and strains of other and unspecified parts of back',
848: 'Other and ill-defined sprains and strains',
850: 'Concussion',
851: 'Cerebral laceration and contusion',
852: 'Subarachnoid, subdural, and extradural hemorrhage, following injury',
853: 'Other and unspecified intracranial hemorrhage following injury',
854: 'Intracranial injury of other and unspecified nature',
855: ' ',
860: 'Traumatic pneumothorax and hemothorax',
861: 'Injury to heart and lung',
862: 'Injury to other and unspecified intrathoracic organs',
864: 'Injury to liver',
866: 'Injury to kidney',
867: 'Injury to pelvic organs',
870: 'Open wound of ocular adnexa',
871: 'Open wound of eyeball',
872: 'Open wound of ear',
873: 'Other open wound of head',
875: 'Open wound of chest (wall)',
876: 'Open wound of back',
877: 'Open wound of buttock',
878: 'Open wound of genital organs (external), including traumatic amputation',
879: 'Open wound of other and unspecified sites, except limbs',
880: 'Open wound of shoulder and upper arm',
881: 'Open wound of elbow, forearm, and wrist',
882: 'Open wound of hand except finger(s) alone',
883: 'Open wound of finger(s)',
884: 'Multiple and unspecified open wound of upper limb',
885: 'Traumatic amputation of thumb (complete) (partial)',
886: 'Traumatic amputation of other finger(s) (complete) (partial)',
887: 'Traumatic amputation of arm and hand (complete) (partial)',
888: ' ',
890: 'Open wound of hip and thigh',
891: 'Open wound of knee, leg [except thigh], and ankle',
892: 'Open wound of foot except toe(s) alone',
893: 'Open wound of toe(s)',
894: 'Multiple and unspecified open wound of lower limb',
895: 'Traumatic amputation of toe(s) (complete) (partial)',
896: 'Traumatic amputation of foot (complete) (partial)',
897: 'Traumatic amputation of leg(s) (complete) (partial)',
901: 'Injury to blood vessels of thorax',
902: 'Injury to blood vessels of abdomen and pelvis',
904: 'Injury to blood vessels of lower extremity and unspecified sites',
905: 'Late effects of musculoskeletal and connective tissue injuries',
907: 'Late effects of injuries to the nervous system',
908: 'Late effects of other and unspecified injuries',
909: 'Late effects of other and unspecified external causes',
910: ' ',
914: ' ',
915: ' ',
916: ' ',
917: ' ',
918: ' ',
919: ' ',
920: 'Contusion of face, scalp, and neck except eye(s)',
921: 'Contusion of eye and adnexa',
922: 'Contusion of trunk',
923: 'Contusion of upper limb',
924: 'Contusion of lower limb and of other and unspecified sites',
925: 'Crushing injury of face, scalp, and neck',
927: 'Crushing injury of upper limb',
928: 'Crushing injury of lower limb',
929: 'Crushing injury of multiple and unspecified sites',
930: 'Foreign body on external eye',
931: 'Foreign body in ear',
932: 'Foreign body in nose',
933: 'Foreign body in pharynx and larynx',
934: 'Foreign body in trachea, bronchus, and lung',
935: 'Foreign body in mouth, esophagus, and stomach',
937: 'Foreign body in anus and rectum',
938: 'Foreign body in digestive system, unspecified',
939: 'Foreign body in genitourinary tract',
940: 'Burn confined to eye and adnexa',
941: 'Burn of face, head, and neck',
942: 'Burn of trunk',
943: 'Burn of upper limb, except wrist and hand',
944: 'Burn of wrist(s) and hand(s)',
945: 'Burn of lower limb(s)',
947: 'Burn of internal organs',
948: 'Burns classified according to extent of body surface involved',
949: 'Burn, unspecified',
950: 'Injury to optic nerve and pathways',
951: 'Injury to other cranial nerve(s)',
953: 'Injury to nerve roots and spinal plexus',
955: 'Injury to peripheral nerve(s) of shoulder girdle and upper limb',
956: 'Injury to peripheral nerve(s) of pelvic girdle and lower limb',
957: 'Injury to other and unspecified nerves',
958: 'Certain early complications of trauma',
959: 'Injury, other and unspecified',
963: 'Poisoning by primarily systemic agents',
964: 'Poisoning by agents primarily affecting blood constituents',
965: 'Poisoning by analgesics, antipyretics, and antirheumatics',
969: 'Poisoning by psychotropic agents',
971: 'Poisoning by drugs primarily affecting the autonomic nervous system',
973: 'Poisoning by agents primarily affecting the gastrointestinal system',
977: 'Poisoning by other and unspecified drugs and medicinal substances',
979: 'Poisoning by other vaccines and biological substances',
980: 'Toxic effect of alcohol',
985: 'Toxic effect of other metals',
987: 'Toxic effect of other gases, fumes, or vapors',
988: 'Toxic effect of noxious substances eaten as food',
989: 'Toxic effect of other substances, chiefly nonmedicinal as to source',
990: 'Effects of radiation, unspecified',
991: 'Effects of reduced temperature',
992: 'Effects of heat and light',
993: 'Effects of air pressure',
994: 'Effects of other external causes',
995: 'Certain adverse effects not elsewhere classified',
996: 'Complications peculiar to certain specified procedures',
997: 'Complications affecting specified body systems, not elsewhere classified',
998: 'Other complications of procedures, NEC',
999: 'Complications of medical care, not elsewhere classified',
724412: ' '}

icd9_bucket_to_description = {
0: ' ',        
1: 'infectious and parasitic diseases',
2: 'neoplasms', 
3: 'endocrine, nutritional and metabolic diseases, immunity disorders',
4: 'diseases of the blood and blood-forming organs', 
5: 'mental disorders', 
6: 'diseases of the nervous system and sense organs', 
7: 'diseases of the circulatory system', 
8: 'diseases of the respiratory system', 
9: 'diseases of the digestive system', 
10: 'diseases of the genitourinary system', 
11: 'complications of pregnancy, childbirth, and the puerperium',
12: 'diseases of the skin and subcutaneous tissue',  
13: 'diseases of the musculoskeletal system and connective tissue', 
14: 'congenital anomalies', 
15: 'certain conditions originating in the perinatal period', 
16: 'symptoms, signs, and ill-defined conditions',
17: 'injury and poisoning'}
